spring:
  datasource:
    url: "jdbc:postgresql://localhost:8432/recipe_db"
    username: user
    password: password

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

storage:
  location: prediction_model/data/uploads/
