version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: recipe_db_container

    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    volumes:
      - ./database-data:/var/lib/postgresql/data/

    ports:
      - "8432:5432"