CREATE TABLE public.recipe
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        TEXT,
    instructions TEXT,
    picture_link TEXT,
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);


CREATE TABLE public.ingredient
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      TEXT,
    recipe_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_ingredient PRIMARY KEY (id)
);

ALTER TABLE public.ingredient
    ADD CONSTRAINT FK_INGREDIENT_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES public.recipe (id);